-- AlterTable
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "failureReason" TEXT;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "failureDetail" TEXT;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "failureCategory" TEXT;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "moogoldOrderRef" TEXT;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "paidAt" TIMESTAMP(3);
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "fulfilledAt" TIMESTAMP(3);
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "failedAt" TIMESTAMP(3);
